language: node_js
node_js:
- '10'
sudo: false
install:
- npm install --only=dev
- npm ci
before_script:
- node node_modules/eslint/bin/eslint.js .
script:
- node ./edenconfig.js
after_script:
- npm test
deploy:
  provider: npm
  email: alex@edenup.com
  api_key:
    secure: bqyQdyyRpylsy7yZf22w2mtY/CbJfl1B8N4alSQw6nX6RPF7lNXKxr6CAUUf4zNN46okpHJHZoIS6W2F1va6NSkHn/uRlquQVx22oCn39G6MKRmRsjqj/hKo8M4iUJ+4rY8y3Hgfdha2mAwVx4fvjhZwT15x5pwvGSeMC9Ev3RWuma164gvW2jMgembw87IsXZTjCSUPqtn5yIynzwHDtn68EPujlUZq4GnrNh2I8yH00wMPOKGsAflttE4KoOS0vhuq/PM3eK8FSJUua4+HY11KE4CTaKFAX3mBgn1LOFbhhyZYolpre25RbGnRzwYUf7/IKjfYNq7P8PJo0DBnfaNmG1F2v7TFh1UydmTbm4q+wISWbSwx/V/7lJQiRi7XDgVRXqa/ZlWi3qs7QjyhnImvtqULsZeUrs0/D+lNgqqM/rmniDD379zGMg5oycAwdtUTqCegSOHiPsLB3jPQIksuWIrpHdJl53EQ+p0lprduVeKzlC0+utZ7ZBTSctLLOX3YwzbUjpyEvlo3TrP8gIIN3MwymN0v3/q4laUK4c3poibPkHt3gwAZmw4YWt9iew8plCZGGDFt+evJZJYezmWIDbV4e/gNfnHrg70M3geuarzE8iH9G+BTGAXNz3Pt+wu7SbnyF2Qx0LIVnAoYQUNK8/dx+USoGVJIhuKIoV0=
  on:
    tags: true
    repo: ifactorydigital/ifactoryjs_shop-shipping
